In [8]:
import numpy as np

## Create a ndarray
 

### Creating a rank 1 Array (one dimensional array)

In [18]:
 # Creating a rank 1 Array
arr = np.array([1.3, 2, 3])
print("Array with Rank 1: \n",arr)

Array with Rank 1: 
 [1.3 2.  3. ]


In [20]:
type(arr)

numpy.ndarray

In [22]:
arr.dtype

dtype('float64')

### <span style = "color:maroon"> Note the difference between `type()` and `dtype` </span>

### Creating a rank 2 Array

In [24]:
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)

Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]


In [26]:
print(arr.ndim)
arr.shape

2


(2, 3)

In [30]:
print(arr.reshape(3,2))

arr.reshape(3, 2)
print('\n' ,arr)  #is reshape() an in-place operation?
arr=arr.reshape(3, 2) #reshape and output
print('\n' ,arr)

[[1 2]
 [3 4]
 [5 6]]

 [[1 2 3]
 [4 5 6]]

 [[1 2]
 [3 4]
 [5 6]]


In [34]:
# Creating an array from tuple
arr1 = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)


Array created using passed tuple:
 [[1 2]
 [3 4]
 [5 6]]


### Creating a rank 3 Array

In [32]:
#2 x 2 x 3
rank3 = np.array( [
    [ 
        [1, 2, 3],
        [4, 5, 6] 
    ], 
    [
        [7, 8, 9],
        [10, 11, 12]
    ]    
]
)
rank3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## <font color = crimson> Practice 1 </font>
1. Create a Rank1 ndarray
   
2. Create a Rank2 ndarray

3. Create a Rank3 ndarray

4. Create the following special  ndarrays:
- np.zeros(), (create a 3x3 ndarray filled with 0’s)
- np.full(), (create a 3x2 ndarray filled with 100’s)
- np.ones(), 
- np.eye()


In [36]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
print(list(range(4)))
arr1=np.arange(1,7).reshape(2,3)
arr1
#returns an array of evenly spaced values within a given range. 
#It's very similar to Python's built-in range() function 
#but returns a NumPy array instead of a list.

[0, 1, 2, 3]


array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
arr1=arr1.reshape(3,2)
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

## arange() method
arange() method returns an array with evenly spaced elements 

In [ ]:
print(list(range(4)))

In [ ]:
arr1 = np.arange(4)
arr1

In [ ]:
arr1 = arr1.reshape(2,2)
arr1

In [ ]:
print("A\n", np.arange(4), "\n") 

print("B\n", np.arange(4).reshape(2, 2), "\n") 
print(np.arange(4).reshape(2, 2).shape)
  
print("C\n", np.arange(4, 10), "\n") 
  
print("D\n", np.arange(4, 20, 3), "\n") 

## <font color = crimson> Practice 2 </font>
1. Use the numpy.arange() and numpy.reshape() method to create a 2x3 ndarray containing
   [ [2, 3, 4],[5, 6, 7]]



### numpy.linspace
https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

In [ ]:
np.linspace(1,9,num = 5) # number of datapoints is 5 ( 4 gaps), last number being 9.

In [ ]:
np.linspace(1,9,num = 5, dtype=int) # number of datapoints is 5 (4 gaps), last number being 9.

In [ ]:
# num = 5 and endPoint = False: 6 data points, but 5 visible since the end point not shown. (5 gaps)
# If retStep is True, return (samples, step), where step is the spacing between samples.
np.linspace(1,9,num = 5, endpoint = False, retstep = True) #5 gaps, last number 9 invisible.

In [ ]:
#Graphical illustration different parameters of the linspace function
#Note : for plotting graphs in python, we require libraries like matplotlib
import matplotlib.pyplot as plt

y = np.zeros(5)
x1 = np.linspace(1, 9, num = 5, endpoint=True)
x2 = np.linspace(1, 9, num = 5 , endpoint=False)
plt.figure(figsize=(3, 2))
plt.plot(x1, y, 'o')
plt.plot(x2, y+1, 'o')
plt.ylim(-1,5)
plt.show()
