# <span style="font-family: Arial; color:Crimson; font-style:bold"> Numpy Indexing (2)</span>



In [2]:
import numpy as np

## <span style="font-family: Arial; color:maroon; font-style:bold"> Boolean Indexing -- using filters to create a subsection of a numpy array </span>

## <span style="font-family: Arial; color:orangered; font-style:bold"> 1. Filters </span>

### <span style = "color: #2462C0"> Example 1: Given an ndarray, set all numbers > 15 to be 15. </span>

In [7]:
# create a 3x2 array
array_1 = np.array([[11,12], [21, 22], [34, 32]])

array_1

array([[11, 12],
       [21, 22],
       [34, 32]])

### Step 1: create a filter

In [12]:
# create a filter which will be boolean values for whether each element meets this condition
filter = (array_1 > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

Notice that the filter is a same size ndarray as *an_array*. It is filled with True for each element whose corresponding element in *an_array*  is greater than 15 and False for those elements whose value is less than 15.

### Step 2: Apply the filter to the array. <br>
- Usually this step is not necessary. We are showing **an_array[filter]** only to show the part of the array that meet the filtering condition.  
- Note the difference between an_array[filter].shape and an_array.shape

In [18]:
# we can now apply the filter to the ndarray to select just those elements which meet that criteria
print(array_1[filter])
print(array_1)
#Q: What's the shape of the filtered array?
print(array_1[filter].shape)

[21 22 34 32]
[[11 12]
 [21 22]
 [34 32]]
(4,)


### Step 3: Perform operations on the filtered section.

In [12]:
array_1[filter] = 15
array_1

array([[11, 12],
       [15, 15],
       [15, 15]])

<font color = red> Check out the application of filtering in the image processing notebook <font>

### Step 1 ~ 3 can be combine without the need of the filter variable. 

In [13]:
# create a 3x2 array
array_1 = np.array([[11,12], [21, 22], [34, 32]])

array_1

array([[11, 12],
       [21, 22],
       [34, 32]])

In [14]:
array_1[array_1 > 15] = 15
array_1

array([[11, 12],
       [15, 15],
       [15, 15]])

### <span style = "color: #2462C0">Example 2: Given an ndarray, change all even numbers in a numpy array to 0. </span>

In [15]:
# create a 3x2 array
array_2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

array_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
# verify the filter
filter = (array_2 % 2 == 0)
filter

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [17]:
array_2[filter] = 0
array_2

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0]])

<p style="font-family: Arial; font-size:2.00em;color:#FF5733; font-style:bold"> 
Practice 2 -- Filtering
</p>

1. Create a rank-1 array containing 16 numbers from [-5, 10].
2. Reshape the array to 4 x 4
3. Set all non-zero elements below 10 to be 0.

In [18]:
array_3 = np.arange(-5, 11)
array_3 = array_3.reshape(4,4)
filter = array_3 < 0
array_3[filter] = 0
array_3

array([[ 0,  0,  0,  0],
       [ 0,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])


## <span style="font-family: Arial; color:orangered; font-style:bold"> 2. Logical Operations for Numpy Arrays:  </span>

1. Use either <b>numpy.logical_and() </b>, <b>numpy.logical_or()</b>, or <b>numpy.logical_not()</b> to perform logical operations on numpy arrays.
   
2. Note that you cannot use <b>"and"</b>, <b>"or"</b>, or <b>"not"</b> to perform logical operations on numpy arrays.  

3. Alternatively, you can use bit-wise operator <b>&</b> and <b>|</b> in place of <b>numpy.logical_and() </b>and <b>numpy.logical_or() 

4. When using <b>&</b> and <b>|</b>, you must add a pair of <b> ( ) </b>.


In [19]:
x = np.arange(5)
print(x)
filter1 = np.logical_and(x > 1, x <= 4)
print(filter1)


[0 1 2 3 4]
[False False  True  True  True]


In [70]:
#Alternatively:
filter2 = (x > 1) & (x <= 4) 
#filter2 = x > 1 & x <= 4 

print(filter2)

[False False  True  True  True]


### <span style = "color:orangered"> Notes </span>

#### 1. Note that you cannot use <b>"and"</b>, <b>"or"</b>, or <b>"not"</b> to perform logical operations on numpy arrays. </br>
This is because each operand of <b>"and"</b>, <b>"or"</b>, or <b>"not"</b> must be one single logical value (True/False), but (x > 1) in the following example returns an ndarray.

In [68]:
x = np.arange(5)
print(x)

#filter3 = (x > 1) and (x <= 4)
filter3 = (x > 1) & (x <= 4)

#filter3 = not(x > 1)
filter3 != (x > 1)
print(filter3)

[0 1 2 3 4]
[False False  True  True  True]


#### 2. When using <b>&</b> and <b>|</b>, you must add a pair of <b> ( ) </b>.

In [64]:
x = np.arange(5)
print(x)

#filter = (x > 1 & x < 4) 

#Q: How do you fix it?
filter = (x > 1) & (x < 4) 
filter

[0 1 2 3 4]


array([False, False,  True,  True, False])

#### Explanations

In [31]:
print(bin(4))
print(bin(5))

0b100
0b101


In [32]:

4 & 5 #bit-wise operator.

4

In [33]:
#bin() convert a number to binary
print (bin(4))
print( bin(5))
print(bin(4 & 5))


0b100
0b101
0b100


<p style="font-family: Arial; font-size:2.75em;color:#FF5733; font-style:bold"><br>
Practice
<br></p> 

1. Create a rank-1 array containing 12 numbers from -1 to 10, inclusive.
2. reshape the array to 3 x 4
3. Use the '&' operator to create a filter for all <b>even</b> elements that are not 10. Show the filter
4. Use <b> np.logical_and()</b> to do the same thing specified at step 3.
5. Increase all elements that meet the above condition by 100

In [56]:
array=np.arange(-1,11)
print(array)

x=array.reshape(3,4)
print(x)

#filter=(x % 2==0)&(x != 10)
#print(filter)
filter=np.logical_and(x % 2==0,x != 10)
print(filter)

x[filter] +=100
print(x)

[-1  0  1  2  3  4  5  6  7  8  9 10]
[[-1  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]
[[False  True False  True]
 [False  True False  True]
 [False  True False False]]
[[ -1 100   1 102]
 [  3 104   5 106]
 [  7 108   9  10]]


In [135]:
a=np.arange(6)
a=a.reshape(2,3)

In [137]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [123]:
a.sum(axis=1)
#代表行方向进行求和row

array([ 3, 12])

In [139]:
a.sum(axis=0)
#a.sum(axis=0) 代表列方向进行求和column

array([3, 5, 7])

In [131]:
np.sum(a,axis=0)
#a代表求和数组
#axis=0代表列求和
#axis=1代表行求和

array([3, 5, 7])

In [141]:
np.sum(a,axis=1)

array([ 3, 12])