# <span style="font-family: Arial; color:Crimson; font-style:bold"> Numpy Indexing (1) </span>



## <span style="font-family: Arial; color:maroon; font-style:bold"> Array Creation </span>

### <p style="font-family: Arial; color:#2462C0; font-style:bold"> How to create Rank 1 numpy arrays:
</p>

In [13]:
import numpy as np

an_array = np.array([3, 33, 333])  # Create a rank 1 array

print(type(an_array))              # The type of an ndarray is: "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


In [15]:
# test the shape of the array we just created, it should have just one dimension (Rank 1)
print(an_array.shape)

(3,)


In [17]:
# because this is a 1-rank array, we need only one index to accesss each element
print(an_array[0], an_array[1], an_array[2]) 

3 33 333


In [19]:
an_array[0] =888            # ndarrays are mutable, here we change an element of the array

print(an_array)

[888  33 333]


### <p style="font-family: Arial; color:#2462C0; font-style:bold"> How to create a Rank 2 numpy array:</p>

A rank 2 **ndarray** is one with two dimensions.  Notice the format below: 

[ [row] , [row] ]

2 dimensional arrays are great for representing matrices which are often useful in data science.

In [22]:
another = np.array([[11,12,13],[21,22,23]])   # Create a rank 2 array

print(another)  # print the array

print("The shape is 2 rows, 3 columns: ", another.shape)  # rows x columns                   

print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", another[0, 0], ", ",another[0, 1],", ", another[1, 0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray:  11 ,  12 ,  21


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
There are many way to create numpy arrays:
</p>

Here we create a number of different size arrays with different shapes and different pre-filled values.  numpy has a number of built in methods which help us quickly and easily create multidimensional arrays.

In [25]:
import numpy as np

# create a 2x2 array of zeros
ex1 = np.zeros((2,2))      
print(ex1)                              

[[0. 0.]
 [0. 0.]]


In [27]:
# create a 2x2 array filled with 9.0
ex2 = np.full((2,2), 9.0)  
print(ex2)   

[[9. 9.]
 [9. 9.]]


In [29]:
# create a 2x2 identity matrix, which is a matrix with the diagonal 1s and the others 0
ex3 = np.eye(2,2)
print(ex3)  

[[1. 0.]
 [0. 1.]]


In [31]:
# create an array of ones
ex4 = np.ones((1,2))
print(ex4)    

[[1. 1.]]


In [33]:
# notice that the above ndarray (ex4) is actually rank 2, it is a 1x2 array
print(ex4.shape)

# which means we need to use two indexes to access an element
print()
print(ex4[0,1])

(1, 2)

1.0


In [35]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((2,2))
print(ex5)    

[[0.14690896 0.04528484]
 [0.27933032 0.26268628]]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Reshaping array:
</p>

In [38]:
# grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr, arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] (20,)


In [40]:
# reshape to be a 4 x 5 matrix
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Transpose:

</p>

In [43]:
# transpose
ex1 = np.array([[11,12],[21,22]])
print("ex1:\n", ex1)
ex1.T

ex1:
 [[11 12]
 [21 22]]


array([[11, 21],
       [12, 22]])

## <span style="font-family: Arial; color:maroon; font-style:bold"> Array Indexing
</span>

In [46]:
import numpy as np

# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], 
                     [21,22,23,24], 
                     [31,32,33,34]])
print(an_array)
 

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


### <span style="font-family: Arial; color:#2462C0; font-style:bold"> Integer indexing:
</span>

In [49]:
an_array[1,1]

22

### <span style="font-family: Arial; color:#2462C0; font-style:bold"> Slice indexing:
</span>

Similar to the use of slice indexing with lists and strings, we can use slice indexing to pull out sub-regions of ndarrays.

Use array slicing to get a subarray consisting of the first two rows and the middle two columns.

In [53]:
a_slice = an_array[:2, 1:3]
print(type(a_slice))

<class 'numpy.ndarray'>


### <span style="font-family: Arial; color:#2462C0; font-style:bold">When you modify a slice, the modification occurs on the array  </span>

In [56]:
print("Before:\n", an_array)   #inspect an_array 
a_slice[0, 0] = 1000    # a_slice[0, 0] is the same piece of data as an_array[0, 1]
print("After:\n", an_array)    

Before:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
After:
 [[  11 1000   13   14]
 [  21   22   23   24]
 [  31   32   33   34]]


<font color = red> Check out the application of slicing index in the image processing notebook <font>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Use both integer indexing & slice indexing
</p>

We can use combinations of integer indexing and slice indexing to create different shaped matrices.

In [60]:
# Create a Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], 
                     [21,22,23,24], 
                     [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [62]:
# Using both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array[1, :]    # Rank 1 view 

print(row_rank1, row_rank1.shape)  # notice only a single []

[21 22 23 24] (4,)


In [64]:
# Slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2, :]  # Rank 2 view 

print(row_rank2, row_rank2.shape)   # Notice the [[ ]]

[[21 22 23 24]] (1, 4)


In [66]:
#We can do the same thing for columns of an array:

col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)  # Rank 1 []
print()
print(col_rank2, col_rank2.shape)  # Rank 2 [[]]

[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [87]:
# importing all the required libraries
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image, ImageOps

#source: https://www.analyticsvidhya.com/blog/2021/05/image-processing-using-numpy-with-practical-implementation-and-code/?

In [96]:
img = np.array(Image.open('ds_python/Numpy/EmmaStone.jpg'))
plt.figure(figsize=(5,5))
plt.imshow(img)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/dingdingjiang/LABS/ds_python/ds_python/Numpy/EmmaStone.jpg'

In [76]:
print('# of dims: ',img.ndim)     # dimension of an image
print('Img shape: ',img.shape)    # shape of an image
print('Dtype: ',img.dtype)
print(img[20, 20])                # pixel value at [R, G, B]
print(img[450, 700])
#print(img[:, :, 2].min()) 

NameError: name 'img' is not defined

### slicing operations

In [79]:
img = np.array(Image.open('EmmaStone.jpg'))
fig = plt.figure(figsize=(10, 10))
fig.add_subplot(1, 2, 1)

#Show original image
plt.imshow(img)
plt.title('Original')

#show trimmed image
#img0 = img[128:-128, 128:-128, :] #-128, 128 from the end of the last row/column
#img0=[255,255,255] Not broadcasting but assignment
#img0[:]=255

#img[128:-128, 128:-128, :]=255
img[128:-128, 128:-128, 2]=255

fig.add_subplot(1, 2, 2)
plt.imshow(img0)
plt.title('Trimmed')

FileNotFoundError: [Errno 2] No such file or directory: '/Users/dingdingjiang/LABS/ds_python/EmmaStone.jpg'

<p style="font-family: Arial; font-size:2.75em;color:#FF5733; font-style:bold"><br>
Practice
<br></p> 

1. Create a rank-1 array containing 16 numbers from 1 to 16, inclusive.
2. Reshape the array to 4 x 4
3. Show the 2x2 sub-array of the bottom right corner
4. Show the last line of the array as a rank-1 array with a shape (4,) 
   as well as a rank-2 array with a shape (4,1) respectively