## Numpy Broadcasting

Broadcasting is a powerful feature in NumPy that allows arrays of different shapes to be used in arithmetic operations without explicitly reshaping or copying data. It enables efficient computations by automatically expanding smaller arrays to match larger ones.
How Does Broadcasting Work?
When performing operations between two arrays of different shapes, NumPy tries to match their shapes using the following rules:
1. If the arrays have different numbers of dimensions, the smaller array is padded with extra dimensions on the left.
2. If the sizes of dimensions don’t match, the dimension with size `1` is stretched to match the other array.
3. If the sizes don’t match and neither is `1`, NumPy throws an error.


In [3]:
import numpy as np

### Case 1: Broadcasting a Scalar (Single Number)

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2,3)
print(arr.shape)
arr

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
result = arr + 10  # 10 is a scalar (Shape: ())
result

array([[11, 12, 13],
       [14, 15, 16]])

### Case 2: Broadcasting a 1D Array to a 2D Array

In [11]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
vec = np.array([10, 20, 30])  # Shape (1,3)
vec

array([10, 20, 30])

In [15]:
result = arr + vec  # vec is broadcasted to shape (2,3)
result
#vec expands it to (2,3) by repeating the row to match arr.

array([[11, 22, 33],
       [14, 25, 36]])

### Case 3: Broadcasting a Column Vector to a 2D Array

In [18]:
print(arr.shape)
arr

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
col_vec = np.array([[10], [20]])  # Shape (2,1)

result = arr + col_vec  # col_vec is broadcasted to shape (2,3)
result
#col_vec (2,1) expands its 1-column to match arr (2,3), applying element-wise addition.

array([[11, 12, 13],
       [24, 25, 26]])

### Case 4: Incomparible Shapes (Error)

In [23]:
print(arr.shape)
arr

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
wrong_shape = np.array([10, 20])  # Shape (1,2)

result = arr + wrong_shape  # ❌ Error!


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

## 🔷 **Broadcasting Rules Summary**

✅ **Rule 1**: If the two arrays have a different number of dimensions, add extra dimensions on the **left** to match.  
✅ **Rule 2**: If a dimension is **1** in one array and a larger number in the other, **stretch** the **1** dimension.  
❌ **Rule 3**: If dimensions **don’t match and neither is 1**, NumPy raises an **error**.

| **Shape 1** | **Shape 2** | **Broadcasted Shape** | **Works?** |
|------------|------------|----------------------|------------|
| (3, 3)     | (3, 3)     | (3, 3)               | ✅ Yes      |
| (3, 3)     | (3,)       | (3, 3)               | ✅ Yes      |
| (3, 3)     | (1, 3)     | (3, 3)               | ✅ Yes      |
| (3, 3)     | (3, 1)     | (3, 3)               | ✅ Yes      |
| (3, 3)     | (2, 3)     | ❌ Error             | ❌ No       |


（3，3）&（2，3）neither has a size of 1 in the first dimension